"""SQLite access: connections, schemas, migrations.

Concurrency model (PLAN 2 section 11). Several server processes run at once -
one per editor window, one per terminal session - all against the same store.
So: WAL, a generous busy timeout, retry-with-backoff on write, and short write
transactions. Bulk work happens under the indexer lease (see lease.py), not in
a long-held transaction.

Durable vs rebuildable (PLAN 2 section 3): everything in repo.db is durable.
That includes `files` and `symbols`, which may look derivable from source but
are not - a tombstone for a deleted symbol (PLAN.md section 4) cannot be
regenerated by parsing code that no longer contains it. Only the FTS index and
parse artifacts are genuinely rebuildable.

Deletion policy (PLAN.md section 10): no ON DELETE CASCADE anywhere in the
durable graph. Losing a symbol row must never take its warnings, decisions and
bug history with it. Durable entities are tombstoned, never deleted.
"""

from __future__ import annotations

import json
import sqlite3
import time
from pathlib import Path
from typing import Any, Iterable

SCHEMA_VERSION = 8

# Columns added after a schema version shipped. Migration is first-class
# (PLAN.md section 11): additive, idempotent, and never destructive.
ADDED_COLUMNS: list[tuple[str, str, str]] = [
    ("symbols", "calls_raw", "TEXT"),
    ("symbols", "token_signature", "TEXT"),
    # Usage signal. A memory that agents keep opening has proven itself in a
    # way no authored severity can; one nobody has ever opened has not.
    ("memories", "access_count", "INTEGER DEFAULT 0"),
    ("memories", "last_accessed_at", "TEXT"),
    ("memories", "surfaced_count", "INTEGER DEFAULT 0"),
    # Import resolution is a second pass, like call resolution, so the raw
    # specs have to survive on the file row between the two.
    ("files", "imports_raw", "TEXT"),
    # Decorators are what make an entry point recognisable.
    ("symbols", "decorators", "TEXT"),
    # Which extractor version last wrote this file's rows. NULL means "before
    # this column existed", which is older than any real version.
    ("files", "extract_version", "INTEGER"),
    # Which extractor version computed this anchor's fingerprints. Lets a
    # change to the fingerprint ALGORITHM be told apart from a change to the
    # code, so improving the extractor does not cost the store its trust.
    ("anchors", "extract_version", "INTEGER"),
    # Receiver name -> possible types, the evidence the receiver_typed call
    # tier resolves through.
    ("symbols", "receiver_types", "TEXT"),
]

BUSY_TIMEOUT_MS = 15000
WRITE_RETRIES = 8


CATALOG_SCHEMA = """
CREATE TABLE IF NOT EXISTS repositories (
    repo_id             TEXT PRIMARY KEY,
    name                TEXT,
    status              TEXT NOT NULL DEFAULT 'ACTIVE',
    vcs                 TEXT NOT NULL DEFAULT 'git',
    identity_strength   TEXT NOT NULL DEFAULT 'strong',
    project_id          TEXT,
    created_at          TEXT NOT NULL,
    last_seen_at        TEXT,
    last_indexed_commit TEXT
);

-- A repository is known by many mutable names. None of them is its identity.
CREATE TABLE IF NOT EXISTS repository_aliases (
    repo_id       TEXT NOT NULL REFERENCES repositories(repo_id),
    alias_kind    TEXT NOT NULL,   -- remote | project_id | root_commit | path
    alias         TEXT NOT NULL,
    first_seen_at TEXT NOT NULL,
    PRIMARY KEY (repo_id, alias_kind, alias)
);
CREATE INDEX IF NOT EXISTS idx_alias_lookup ON repository_aliases(alias_kind, alias);

CREATE TABLE IF NOT EXISTS checkouts (
    checkout_id     TEXT PRIMARY KEY,
    repo_id         TEXT NOT NULL REFERENCES repositories(repo_id),
    path            TEXT NOT NULL UNIQUE,
    git_common_dir  TEXT,
    is_worktree     INTEGER NOT NULL DEFAULT 0,
    status          TEXT NOT NULL DEFAULT 'ACTIVE',
    last_head       TEXT,
    last_seen_at    TEXT,
    created_at      TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_checkout_repo ON checkouts(repo_id);

CREATE TABLE IF NOT EXISTS repo_relationships (
    from_repo  TEXT NOT NULL,
    to_repo    TEXT NOT NULL,
    kind       TEXT NOT NULL,   -- FORKED_FROM | MIRROR_OF | RELATED_TO
    confidence REAL,
    evidence   TEXT,
    created_at TEXT NOT NULL,
    PRIMARY KEY (from_repo, to_repo, kind)
);

-- Entity stubs. These outlive their repo store. PLAN.md section 8: when a
-- repo.db is gone, the stub still knows enough to say what the thing was.
CREATE TABLE IF NOT EXISTS entity_refs (
    entity_id  TEXT PRIMARY KEY,
    repo_id    TEXT NOT NULL,
    kind       TEXT NOT NULL,   -- symbol | file | memory
    snapshot   TEXT,            -- json: last known path/name/signature/commit
    status     TEXT NOT NULL DEFAULT 'ACTIVE',
    updated_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_entity_repo ON entity_refs(repo_id);

CREATE TABLE IF NOT EXISTS cross_repo_edges (
    edge_id           TEXT PRIMARY KEY,
    from_entity       TEXT NOT NULL,
    to_entity         TEXT NOT NULL,
    kind              TEXT NOT NULL,
    edge_class        TEXT NOT NULL DEFAULT 'asserted',
    status            TEXT NOT NULL DEFAULT 'ACTIVE',
    confidence        REAL,
    evidence          TEXT,
    target_snapshot   TEXT,
    valid_from_commit TEXT,
    valid_until_commit TEXT,
    created_at        TEXT NOT NULL,
    last_verified_at  TEXT
);

CREATE TABLE IF NOT EXISTS memory_registry (
    memory_id  TEXT PRIMARY KEY,
    repo_id    TEXT NOT NULL,
    kind       TEXT,
    severity   TEXT,
    status     TEXT,
    summary    TEXT,
    updated_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_memreg_repo ON memory_registry(repo_id);

CREATE TABLE IF NOT EXISTS lifecycle_events (
    event_id     INTEGER PRIMARY KEY AUTOINCREMENT,
    subject_id   TEXT NOT NULL,
    subject_kind TEXT NOT NULL,
    from_status  TEXT,
    to_status    TEXT,
    reason       TEXT,
    detail       TEXT,
    at           TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_lifecycle_subject ON lifecycle_events(subject_id);
"""


REPO_SCHEMA = """
-- ---------------------------------------------------------------- code graph
CREATE TABLE IF NOT EXISTS files (
    file_id           TEXT PRIMARY KEY,
    path              TEXT NOT NULL UNIQUE,
    lang              TEXT,
    size              INTEGER,
    content_hash      TEXT,
    status            TEXT NOT NULL DEFAULT 'ACTIVE',  -- ACTIVE | DELETED
    first_seen_commit TEXT,
    last_seen_commit  TEXT,
    deleted_at_commit TEXT,
    indexed_at        TEXT,
    imports_raw       TEXT,
    extract_version   INTEGER
);
CREATE INDEX IF NOT EXISTS idx_files_status ON files(status);

CREATE TABLE IF NOT EXISTS symbols (
    symbol_id            TEXT PRIMARY KEY,
    file_id              TEXT NOT NULL,
    name                 TEXT NOT NULL,
    symbol_path          TEXT NOT NULL,
    kind                 TEXT,
    lang                 TEXT,
    signature            TEXT,
    ast_path             TEXT,
    start_byte           INTEGER,
    end_byte             INTEGER,
    line_start           INTEGER,
    line_end             INTEGER,
    content_fingerprint  TEXT,
    skeleton_fingerprint TEXT,
    prev_fingerprint     TEXT,
    next_fingerprint     TEXT,
    token_signature      TEXT,
    calls_raw            TEXT,
    decorators           TEXT,
    receiver_types       TEXT,
    status               TEXT NOT NULL DEFAULT 'ACTIVE',  -- ACTIVE | DELETED
    last_known_path      TEXT,
    last_seen_commit     TEXT,
    deleted_at_commit    TEXT,
    updated_at           TEXT
);
CREATE INDEX IF NOT EXISTS idx_sym_path   ON symbols(symbol_path);
CREATE INDEX IF NOT EXISTS idx_sym_name   ON symbols(name);
CREATE INDEX IF NOT EXISTS idx_sym_fp     ON symbols(content_fingerprint);
CREATE INDEX IF NOT EXISTS idx_sym_skel   ON symbols(skeleton_fingerprint);
CREATE INDEX IF NOT EXISTS idx_sym_file   ON symbols(file_id);
CREATE INDEX IF NOT EXISTS idx_sym_status ON symbols(status);

-- Edges carry validity, not just existence (PLAN.md sections 5 and 6).
CREATE TABLE IF NOT EXISTS code_edges (
    edge_id            TEXT PRIMARY KEY,
    from_id            TEXT NOT NULL,
    to_id              TEXT NOT NULL,
    kind               TEXT NOT NULL,
    edge_class         TEXT NOT NULL DEFAULT 'deterministic',
    status             TEXT NOT NULL DEFAULT 'ACTIVE',
    confidence         REAL DEFAULT 1.0,
    source             TEXT,
    valid_from_commit  TEXT,
    valid_until_commit TEXT,
    created_at         TEXT,
    last_verified_at   TEXT
);
CREATE INDEX IF NOT EXISTS idx_cedge_from ON code_edges(from_id);
CREATE INDEX IF NOT EXISTS idx_cedge_to   ON code_edges(to_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_cedge_uniq ON code_edges(from_id, to_id, kind);

-- Call sites resolution refused to guess at. Without this table an ambiguous
-- callee is indistinguishable from a callee nobody calls, so "no callers" reads
-- as proof of none. Every row here is a caller some query cannot show you, which
-- is what lets a result say lower-bound instead of quietly claiming exact.
CREATE TABLE IF NOT EXISTS unresolved_calls (
    from_id    TEXT NOT NULL,          -- the calling symbol
    leaf       TEXT NOT NULL,          -- last dotted segment of the callee
    callee_raw TEXT NOT NULL,          -- as written at the call site
    reason     TEXT NOT NULL,          -- ambiguous | external
    candidates INTEGER NOT NULL DEFAULT 0,
    commit_id  TEXT,
    PRIMARY KEY (from_id, callee_raw)
);
CREATE INDEX IF NOT EXISTS idx_unres_leaf ON unresolved_calls(leaf);
CREATE INDEX IF NOT EXISTS idx_unres_from ON unresolved_calls(from_id);

-- Where control enters this program: routes, MCP tool handlers, CLI commands,
-- tests. A call graph with no entry points is a pile of edges - these are the
-- roots that turn it into flows anyone can follow.
CREATE TABLE IF NOT EXISTS entry_points (
    symbol_id TEXT PRIMARY KEY,
    kind      TEXT NOT NULL,          -- route | tool | cli | test | event
    detail    TEXT,                   -- verb+path, tool name, command name
    evidence  TEXT,                   -- what proved it: the decorator, the path
    commit_id TEXT
);
CREATE INDEX IF NOT EXISTS idx_entry_kind ON entry_points(kind);

-- Structure-based functional areas over the call graph. Distinct from
-- knowledge hotspots, which measure where memories cluster: an area can be
-- large and important while carrying no recorded knowledge at all, and that
-- gap is exactly what a newcomer needs pointed out.
CREATE TABLE IF NOT EXISTS communities (
    symbol_id    TEXT PRIMARY KEY,
    community_id INTEGER NOT NULL,
    computed_at  TEXT
);
CREATE INDEX IF NOT EXISTS idx_comm_id ON communities(community_id);

-- ------------------------------------------------------------- memory graph
-- The raw agent write, stored verbatim and never edited. Every derived fact
-- points back here, so the memory system itself stays debuggable.
CREATE TABLE IF NOT EXISTS events (
    event_id   TEXT PRIMARY KEY,
    kind       TEXT NOT NULL,
    payload    TEXT NOT NULL,
    summary    TEXT,
    agent      TEXT,
    client     TEXT,
    commit_sha TEXT,
    branch     TEXT,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS memories (
    memory_id            TEXT PRIMARY KEY,
    kind                 TEXT NOT NULL,
    title                TEXT,
    body                 TEXT NOT NULL,
    severity             TEXT NOT NULL DEFAULT 'medium',
    authority            TEXT NOT NULL DEFAULT 'agent',   -- agent | human | derived
    confidence           REAL NOT NULL DEFAULT 0.8,
    status               TEXT NOT NULL DEFAULT 'ACTIVE',
    scope                TEXT NOT NULL DEFAULT 'repo',
    source_event         TEXT,
    version              INTEGER NOT NULL DEFAULT 1,
    created_at           TEXT NOT NULL,
    updated_at           TEXT,
    created_commit       TEXT,
    last_verified_commit TEXT,
    last_verified_at     TEXT,
    valid_from           TEXT,
    valid_until          TEXT
);
CREATE INDEX IF NOT EXISTS idx_mem_kind   ON memories(kind);
CREATE INDEX IF NOT EXISTS idx_mem_status ON memories(status);

CREATE TABLE IF NOT EXISTS memory_versions (
    memory_id  TEXT NOT NULL,
    version    INTEGER NOT NULL,
    kind       TEXT,
    body       TEXT,
    severity   TEXT,
    status     TEXT,
    changed_at TEXT NOT NULL,
    changed_by TEXT,
    reason     TEXT,
    PRIMARY KEY (memory_id, version)
);

CREATE TABLE IF NOT EXISTS anchors (
    anchor_id            TEXT PRIMARY KEY,
    memory_id            TEXT NOT NULL,
    target_kind          TEXT NOT NULL,   -- symbol | file | repo
    symbol_id            TEXT,
    file_id              TEXT,
    file_path            TEXT,
    symbol_path          TEXT,
    ast_path             TEXT,
    range_start_byte     INTEGER,
    range_end_byte       INTEGER,
    line_start           INTEGER,
    line_end             INTEGER,
    content_fingerprint  TEXT,
    skeleton_fingerprint TEXT,
    prev_fingerprint     TEXT,
    next_fingerprint     TEXT,
    commit_observed      TEXT,
    anchor_confidence    REAL NOT NULL DEFAULT 1.0,
    status               TEXT NOT NULL DEFAULT 'ACTIVE',
    last_verified_commit TEXT,
    last_verified_at     TEXT,
    reanchor_history     TEXT,
    created_at           TEXT NOT NULL,
    extract_version      INTEGER
);
CREATE INDEX IF NOT EXISTS idx_anchor_mem    ON anchors(memory_id);
CREATE INDEX IF NOT EXISTS idx_anchor_sym    ON anchors(symbol_id);
CREATE INDEX IF NOT EXISTS idx_anchor_status ON anchors(status);
CREATE INDEX IF NOT EXISTS idx_anchor_fp     ON anchors(content_fingerprint);

CREATE TABLE IF NOT EXISTS memory_edges (
    edge_id            TEXT PRIMARY KEY,
    from_id            TEXT NOT NULL,
    to_id              TEXT NOT NULL,
    kind               TEXT NOT NULL,
    edge_class         TEXT NOT NULL DEFAULT 'asserted',
    status             TEXT NOT NULL DEFAULT 'ACTIVE',
    confidence         REAL,
    source             TEXT,
    evidence           TEXT,
    valid_from_commit  TEXT,
    valid_until_commit TEXT,
    created_at         TEXT NOT NULL,
    last_verified_at   TEXT
);
CREATE INDEX IF NOT EXISTS idx_medge_from ON memory_edges(from_id);
CREATE INDEX IF NOT EXISTS idx_medge_to   ON memory_edges(to_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_medge_uniq ON memory_edges(from_id, to_id, kind);

CREATE TABLE IF NOT EXISTS corrections (
    correction_id TEXT PRIMARY KEY,
    memory_id     TEXT NOT NULL,
    action        TEXT NOT NULL,
    reason        TEXT,
    actor         TEXT,
    detail        TEXT,
    created_at    TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS investigations (
    investigation_id TEXT PRIMARY KEY,
    query            TEXT NOT NULL,
    intent           TEXT,
    commit_sha       TEXT,
    frontier         TEXT,
    results          TEXT,
    created_at       TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS agit_checkpoints (
    checkpoint_id TEXT PRIMARY KEY,
    agit_commit   TEXT NOT NULL,
    message       TEXT,
    files         TEXT,
    repo_commit   TEXT,
    created_at    TEXT NOT NULL
);

-- FTS lives here rather than in cache/ so every query is a plain join. It is
-- still rebuildable: reindex_fts() regenerates it from `symbols`/`memories`.
CREATE VIRTUAL TABLE IF NOT EXISTS fts_symbols USING fts5(
    symbol_id UNINDEXED, symbol_path, name, signature, body,
    tokenize = "unicode61 remove_diacritics 2"
);
CREATE VIRTUAL TABLE IF NOT EXISTS fts_memories USING fts5(
    memory_id UNINDEXED, title, body, kind,
    tokenize = "unicode61 remove_diacritics 2"
);
"""


def connect(path: Path, *, readonly: bool = False) -> sqlite3.Connection:
    """Open a store with the pragmas the concurrency model depends on."""
    path.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(str(path), timeout=BUSY_TIMEOUT_MS / 1000.0, isolation_level=None)
    conn.row_factory = sqlite3.Row
    conn.execute(f"PRAGMA busy_timeout = {BUSY_TIMEOUT_MS}")
    conn.execute("PRAGMA journal_mode = WAL")
    conn.execute("PRAGMA synchronous = NORMAL")
    conn.execute("PRAGMA foreign_keys = ON")
    return conn


def init_catalog(path: Path) -> sqlite3.Connection:
    conn = connect(path)
    _apply_schema(conn, CATALOG_SCHEMA)
    return conn


def init_repo_store(path: Path) -> sqlite3.Connection:
    conn = connect(path)
    _apply_schema(conn, REPO_SCHEMA)
    return conn


def _apply_schema(conn: sqlite3.Connection, schema: str) -> None:
    """Create tables, retrying if another process is mid-create.

    executescript() commits any pending transaction before it runs, so it must
    not be wrapped in write_tx. Concurrent first-open from several processes is
    normal here - every statement is IF NOT EXISTS, so the loser just retries.
    """
    delay = 0.05
    for attempt in range(WRITE_RETRIES):
        try:
            conn.executescript(schema)
            _migrate(conn)
            _backfill_fts(conn)
            _repair_ref_commits(conn)
            _backfill_test_coverage(conn)
            _set_version(conn)
            return
        except sqlite3.OperationalError as exc:
            if ("locked" not in str(exc) and "busy" not in str(exc)) or attempt == WRITE_RETRIES - 1:
                raise
            time.sleep(delay)
            delay *= 2



def _backfill_fts(conn: sqlite3.Connection) -> None:
    """Index any memory that predates the search index.

    A derived index added after the fact is empty for everything already
    stored, and a half-populated FTS table fails silently: search simply
    returns fewer results, with nothing to indicate why. Measured on a real
    store, 25 of 34 memories were invisible to text search.

    Cheap and idempotent - it inserts only what is missing, so it costs one
    indexed anti-join on every open after the first.
    """
    try:
        missing = conn.execute(
            "SELECT m.memory_id, m.title, m.body, m.kind FROM memories m"
            " LEFT JOIN fts_memories f ON f.memory_id = m.memory_id"
            " WHERE f.memory_id IS NULL LIMIT 5000"
        ).fetchall()
    except sqlite3.OperationalError:
        return          # table not created yet on this connection
    if not missing:
        return
    try:
        conn.execute("BEGIN IMMEDIATE")
        conn.executemany(
            "INSERT INTO fts_memories (memory_id, title, body, kind) VALUES (?,?,?,?)",
            [(r[0], r[1] or "", (r[2] or "")[:4000], r[3] or "") for r in missing],
        )
        conn.execute("COMMIT")
    except sqlite3.OperationalError:
        try:
            conn.execute("ROLLBACK")
        except sqlite3.Error:
            pass


# Ref names are not commit ids. A store that recorded one has a permanently
# broken equality test: `unreviewed_caller` compares a symbol's last_seen_commit
# against an anchor's last_verified_commit, so "HEAD" on one side and a real SHA
# on the other reports every governed symbol as unreviewed, forever.
_REF_NAMES = ("HEAD", "head", "@", "ORIG_HEAD", "FETCH_HEAD", "MERGE_HEAD")

_REF_COLUMNS = (
    ("memories", ("created_commit", "last_verified_commit")),
    ("anchors", ("commit_observed", "last_verified_commit")),
    ("symbols", ("last_seen_commit", "deleted_at_commit")),
    ("files", ("first_seen_commit", "last_seen_commit", "deleted_at_commit")),
    ("code_edges", ("valid_from_commit", "valid_until_commit")),
)



# Rule kinds a test can guard. Mirrors compiler._link_test_coverage; kept here
# so the backfill does not import the compiler at schema time.
_GUARDABLE = ("invariant", "warning", "contract", "security", "decision")


def _backfill_test_coverage(conn: sqlite3.Connection) -> None:
    """Create GUARDED_BY edges for events recorded before that linking existed.

    Same failure mode as the FTS backfill: a feature added later leaves every
    earlier row permanently wrong, and the symptom is silent. Here the
    untested-invariant diagnostic kept reporting rules whose test was recorded
    in the very same call - which trains people to ignore the finding.

    Reconstructed from source_event, so it only ever links a rule to a test the
    author actually recorded alongside it. Idempotent.
    """
    try:
        pairs = conn.execute("""
            SELECT r.memory_id AS rule_id, t.memory_id AS test_id
            FROM memories r
            JOIN memories t ON t.source_event = r.source_event
            WHERE r.kind IN (?,?,?,?,?) AND t.kind = 'test_evidence'
              AND r.status='ACTIVE' AND t.status='ACTIVE'
              AND r.source_event IS NOT NULL
              -- Imports share one synthetic event id, so joining on it would
              -- claim every imported test covers every imported rule. Measured
              -- on a 48-memory import: 264 false coverage claims, which is
              -- worse than none because it silences the untested-rule check.
              AND r.source_event NOT LIKE 'import:%' 
              AND NOT EXISTS (
                  SELECT 1 FROM memory_edges e
                  WHERE e.from_id = r.memory_id AND e.to_id = t.memory_id
                    AND e.kind = 'GUARDED_BY')
            LIMIT 2000
        """, _GUARDABLE).fetchall()
    except sqlite3.OperationalError:
        return
    if not pairs:
        return

    from datetime import datetime, timezone
    stamp = datetime.now(timezone.utc).isoformat(timespec="milliseconds")
    try:
        conn.execute("BEGIN IMMEDIATE")
        conn.executemany(
            "INSERT OR IGNORE INTO memory_edges (edge_id, from_id, to_id, kind, edge_class,"
            " status, confidence, source, created_at)"
            " VALUES (?,?,?,'GUARDED_BY','asserted','ACTIVE',0.9,'backfill',?)",
            [("edge_bf" + rule[-8:] + test[-8:], rule, test, stamp) for rule, test in pairs],
        )
        conn.execute("COMMIT")
    except sqlite3.OperationalError:
        try:
            conn.execute("ROLLBACK")
        except sqlite3.Error:
            pass

def _repair_ref_commits(conn: sqlite3.Connection) -> None:
    """Null out ref names stored where a commit id belongs.

    NULL is honest - "we do not know which commit" is a state the graph already
    handles, whereas a ref name is a value that compares wrongly forever. Runs
    once per store in practice: after the first pass there is nothing to match.
    """
    placeholders = ",".join("?" for _ in _REF_NAMES)
    try:
        conn.execute("BEGIN IMMEDIATE")
        for table, columns in _REF_COLUMNS:
            for column in columns:
                try:
                    conn.execute(
                        f"UPDATE {table} SET {column} = NULL"
                        f" WHERE {column} IN ({placeholders})", _REF_NAMES)
                except sqlite3.OperationalError:
                    continue        # table or column absent in this schema
        conn.execute("COMMIT")
    except sqlite3.OperationalError:
        try:
            conn.execute("ROLLBACK")
        except sqlite3.Error:
            pass

def _migrate(conn: sqlite3.Connection) -> None:
    """Apply additive column migrations to a store created by an older version.

    Only columns are added, never dropped or retyped. A durable knowledge graph
    must not lose data to a schema bump.
    """
    for table, column, decl in ADDED_COLUMNS:
        exists = one(conn.execute("SELECT name FROM sqlite_master WHERE type='table' AND name=?", (table,)))
        if not exists:
            continue
        columns = {r["name"] for r in conn.execute(f"PRAGMA table_info({table})")}
        if column not in columns:
            conn.execute(f"ALTER TABLE {table} ADD COLUMN {column} {decl}")


def _set_version(conn: sqlite3.Connection) -> None:
    current = conn.execute("PRAGMA user_version").fetchone()[0]
    if current != SCHEMA_VERSION:
        conn.execute(f"PRAGMA user_version = {SCHEMA_VERSION}")


class write_tx:
    """Short write transaction with retry.

    Another process may hold the write lock. `BEGIN IMMEDIATE` takes it up
    front so we fail fast and retry rather than discovering the conflict at
    COMMIT after doing all the work.
    """

    def __init__(self, conn: sqlite3.Connection, retries: int = WRITE_RETRIES):
        self.conn = conn
        self.retries = retries

    def __enter__(self) -> sqlite3.Connection:
        delay = 0.05
        for attempt in range(self.retries):
            try:
                self.conn.execute("BEGIN IMMEDIATE")
                return self.conn
            except sqlite3.OperationalError as exc:
                if "locked" not in str(exc) and "busy" not in str(exc):
                    raise
                if attempt == self.retries - 1:
                    raise
                time.sleep(delay)
                delay *= 2
        raise sqlite3.OperationalError("could not acquire write lock")

    def __exit__(self, exc_type, exc, tb) -> bool:
        if exc_type is None:
            self.conn.execute("COMMIT")
        else:
            try:
                self.conn.execute("ROLLBACK")
            except sqlite3.Error:
                pass
        return False


def rows(cur: Iterable[sqlite3.Row]) -> list[dict[str, Any]]:
    """sqlite3.Row -> plain dicts, so results are JSON-serialisable."""
    return [dict(r) for r in cur]


def one(cur: Iterable[sqlite3.Row]) -> dict[str, Any] | None:
    for r in cur:
        return dict(r)
    return None


def jdump(value: Any) -> str | None:
    return None if value is None else json.dumps(value, ensure_ascii=False)


def jload(value: str | None, default: Any = None) -> Any:
    if not value:
        return default
    try:
        return json.loads(value)
    except (ValueError, TypeError):
        return default
